version: '3.4'

services:
    api:
       build:
          context: '../../'
          dockerfile: 'etc/api/Dockerfile'
          args:
              ROADRUNNER_VERSION: '1.3.1'

       volumes:
          - '../../:/app'
       ports:
          - '0.0.0.0:8080:80'

